esphome:
  name: test-esp-home
  includes:
    - my_custom_component.h
    
esp32:
  board: esp32dev
  framework:
    type: arduino

custom_component:
- lambda: |-
    auto my_custom = new MyCustomComponent();
    return {my_custom};
  components:
  - id: my_custom_id
  
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "v3/PVtd/V5wSZon0f+mmus8HtAN/rOYw9xOSJtVmbUo="

mqtt:
  broker: 192.168.1.152

ota:
  password: "225a74feb7617be0810e5b60b1a8f7d7"

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Esp-Home Fallback Hotspot"
    password: "U0ZVYmGRQ8v5"

captive_portal:
    